databaseChangeLog:
  - changeSet:
      id: 017-CreateUserSettingTable
      author: IFUNMAN
      changes:
        - createTable:
            tableName: user_settings
            columns:
              - column:
                  name: id
                  type: uuid
                  constraints:
                    primaryKey: true
              - column:
                  name: user_id
                  type: uuid
                  constraints:
                    nullable: false
              - column:
                  name: is_confirm_contact_requests
                  type: boolean
                  constraints:
                    nullable: false
              - column:
                  name: created_at
                  type: timestamp
                  constraints:
                    nullable: false
              - column:
                  name: updated_at
                  type: timestamp
                  constraints:
                    nullable: false
        - addForeignKeyConstraint:
            constraintName: fk_user_settings_user_id
            baseTableName: user_settings
            baseColumnNames: user_id
            referencedTableName: users
            referencedColumnNames: id
            onDelete: CASCADE