databaseChangeLog:
  - changeSet:
      id: 026-UserAdminSettingsAndEmployeeInitialize
      author: IFUNMAN
      changes:
        - insert:
            tableName: user_settings
            columns:
              - column:
                  name: id
                  value: 'd390676e-de28-4818-ba60-24d37d7c6b04'
              - column:
                  name: user_id
                  value: '2e3049a1-320c-4ddb-873a-5217cae2e1cd'
              - column:
                  name: is_confirm_contact_requests
                  value: false
              - column:
                  name: contacts_visibility
                  value: 'EVERYONE'
              - column:
                  name: profile_visibility
                  value: 'EVERYONE'
              - column:
                  name: is_searchable
                  value: true
              - column:
                  name: employee_visibility
                  value: 'EVERYONE'
              - column:
                  name: updated_at
                  valueComputed: CURRENT_TIMESTAMP
              - column:
                  name: created_at
                  valueComputed: CURRENT_TIMESTAMP
        - insert:
            tableName: employees
            columns:
              - column:
                  name: id
                  value: 'd5d0e793-162c-4912-a64a-fc77add0bc65'
              - column:
                  name: user_id
                  value: '2e3049a1-320c-4ddb-873a-5217cae2e1cd'
              - column:
                  name: leader_id
                  value: null
              - column:
                  name: department
                  value: null
              - column:
                  name: position
                  value: null
              - column:
                  name: description
                  value: null
              - column:
                  name: work_schedule
                  value: null
              - column:
                  name: updated_at
                  valueComputed: CURRENT_TIMESTAMP
              - column:
                  name: created_at
                  valueComputed: CURRENT_TIMESTAMP